import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import loaclFont from 'next/font/local'

import Navbar from './Navbar'
import GoogleAnalyticsScript from './GoogleAnalyticsScript'

import AuthProvider from './auth/Provider'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500'] })

const poppins = loaclFont({
  src: '../public/fonts/poppins-regular-webfont.woff2',
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Nextjs Tutorial',
  description: 'Generated by create next app',
  // openGraph: {
  //   title: '',
  //   description: '',
  // },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />
      <body
        // className={poppins.className}
        className={poppins.variable}
      >
        <AuthProvider>
          <Navbar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
